app/connectors/FinancialDataConnector.scala
app/controllers/OpenPaymentsController.scala
app/controllers/PaymentHistoryController.scala
app/controllers/VatDetailsController.scala
app/models/errors/ServiceError.scala
app/services/AccountDetailsService.scala
app/services/PaymentsService.scala
app/services/VatDetailsService.scala
build.sbt
test/controllers/OpenPaymentsControllerSpec.scala
test/controllers/PaymentHistoryControllerSpec.scala
test/controllers/VatDetailsControllerSpec.scala
test/services/PaymentsServiceSpec.scala
test/services/VatDetailsServiceSpec.scala

I have not refactored the aspects of the project relating to the Account Details page which are due to be removed in a future story.

BTAT-2773 Refactor services/controllers to use ServiceResponse instead of HttpGetResult

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/config/frontendAppConfig.scala
app/connectors/VatObligationsConnector.scala
app/forms/FeatureSwitchForm.scala
app/models/FeatureSwitchModel.scala
app/services/VatDetailsService.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/views/featureSwitch.scala.html
conf/application.conf
conf/messages
it/connectors/VatObligationsConnectorISpec.scala
it/helpers/IntegrationBaseSpec.scala
it/partials/VatDetailsPageSpec.scala
it/stubs/VatObligationsStub.scala
test/connectors/VatObligationsConnectorSpec.scala
test/connectors/VatSubscriptionConnectorSpec.scala
test/mocks/MockAppConfig.scala
test/services/VatDetailsServiceSpec.scala

Implemented feature switch and configuration for vat-obligations (there is no returns split required here)

BTAT-2988 split out vat obligations configuration and added fearure switch

---

app/connectors/VatObligationsConnector.scala
it/stubs/VatObligationsStub.scala
test/connectors/VatObligationsConnectorSpec.scala

There was initially some confusion around this but for now this needs to be split up so we can continue to use vat-api but also have the correct backend route in place.

Changed obligations route to sit in the right place

---

app/services/PaymentsService.scala
app/services/VatDetailsService.scala
test/models/CustomerInformationSpec.scala
test/services/AccountDetailsServiceSpec.scala
test/services/PaymentsServiceSpec.scala
test/services/VatDetailsServiceSpec.scala

This issue was present on both the what-you-owe page as well as the VAT overview page. A refactor of the related test specs was also done as part of this task as there were various inconsistencies and some tests were in the wrong places.

BTAT-3143 - Corrected logic to ignore negative outstanding payments

---

app/testOnly/connectors/DynamicStubConnector.scala
app/testOnly/controllers/DynamicStubController.scala
app/testOnly/models/SchemaModel.scala
conf/application.conf
conf/testOnly.routes
it/testOnly/connectors/DynamicStubConnectorISpec.scala
it/testOnly/stubs/DynamicStub.scala
test/testOnly/controllers/DynamicStubControllerSpec.scala

added test only routes to support populating FT stub and schemas

financialDataPopulationRoutes

---

app/services/PaymentsService.scala
test/services/PaymentsServiceSpec.scala

If you wish to test this visually, here's a handy bit of JSON with jumbled up due dates:
```
{
"_id" : "/enterprise/financial-data/VRN/987654321/VATC?onlyOpenItems=true",
"schemaId" : "getFinancialData",
"method" : "GET",
"status" : 200,
"response" : {
"idType" : "VRN",
"idNumber" : "987654321",
"regimeType" : "VATC",
"processingDate" : "2018-01-01T01:01:01.000Z",
"financialTransactions" : [
{
"chargeType" : "VAT Return Debit Charge",
"mainType" : "VAT Return Charge",
"periodKey" : "18BB",
"periodKeyDescription" : "ABCD",
"taxPeriodFrom" : "2018-01-01",
"taxPeriodTo" : "2018-01-01",
"originalAmount" : 100.00,
"outstandingAmount" : 100.00,
"items" : [
{
"subItem" : "000",
"dueDate" : "2018-04-05",
"amount" : 100.00
}
]
},
{
"chargeType" : "VAT Return Debit Charge",
"mainType" : "VAT Return …
```

BTAT-3406 Added logic to sort items on the what you owe page

---

app/connectors/httpParsers/PaymentsHttpParser.scala
app/models/payments/ChargeType.scala
app/models/payments/OpenPaymentsModel.scala
conf/messages
test/views/payments/OpenPaymentsViewSpec.scala

1. chargeType = "VAT Inaccuracies in EC Sales"
Label text = "because you have provided innacurate information in your EC sales list"
Follows the existing pattern to show the charges based on their due dates in descending order.
Includes a 'pay now' link, and associated pay-api hand-off to OPS.
2. chargeType = "VAT Failure to Submit EC Sales"
Label text = "because you have not submitted an EC sales list or you have submitted it late"
Follow the existing pattern to show the charges based on their due dates in descending order.
Include a 'pay now' link, and associated pay-api hand-off to OPS.

Added the below charge types

---

app/views/templates/PaymentsHistoryChargeHelper.scala
conf/messages
test/views/payments/PaymentHistoryViewSpec.scala
test/views/templates/PaymentsHistoryChargeHelperSpec.scala

Added:
- CivilEvasionPenalty
- Inaccuracy Pentalty
- Failure to Submit ECSales
- FtnEachpartner
- InaccuraciesFrom2009

Btat 3980 - Adding ChargeTypes to Payment History page

---

app/views/templates/payments/WhatYouOweChargeHelper.scala
app/views/templates/payments/whatYouOweChargeRow.scala.html
test/views/templates/payments/WhatYouOweChargeHelperSpec.scala

Some of the charge types require a date period (from - to) for their charge type descriptions. Currently if we don't receive period dates from the API, these descriptions render with a literal {0}. This fix logs the error and hides the description in those scenarios.

BTAT-5476 Fixed {0} issue for charge descriptions that require a date

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/connectors/ServiceInfoPartialConnector.scala
app/views/certificate/vatCertificate.scala.html
app/views/payments/noPayments.scala.html
app/views/payments/openPayments.scala.html
app/views/payments/paymentHistory.scala.html
app/views/vatDetails/details.scala.html
conf/application.conf
test/connectors/ServiceInfoPartialConnectorSpec.scala
test/mocks/MockAppConfig.scala
test/views/certificate/VatCertificateViewSpec.scala
test/views/payments/NoPaymentsViewSpec.scala
test/views/payments/OpenPaymentsViewSpec.scala
test/views/payments/PaymentHistoryViewSpec.scala
test/views/vatDetails/VatDetailsViewSpec.scala

As part of this PR I have also made the serviceInfoContent parameter in the views defaulted to empty HTML, for future proofing of the app in case agents are allowed into these pages going forward, and also to make the view specs a little nicer as we don't have to provide any extra HTML.

BTAT-6135 Updated BTA nav link partial config

---

app/common/FinancialTransactionsConstants.scala
app/models/payments/TransactionSubItem.scala
app/models/viewModels/PaymentsHistoryModel.scala
it/connectors/FinancialDataConnectorISpec.scala
it/pages/LanguageSpec.scala
it/pages/PaymentsPageSpec.scala
it/pages/VatDetailsPageSpec.scala
it/stubs/FinancialDataStub.scala
test/connectors/httpParsers/PaymentsHistoryHttpParserSpec.scala
test/models/PaymentsHistoryModelSpec.scala

The unit and IT test data for FinancialData has also been slightly updated to be more accurate with regards to how the real data is returned.
**NOTE** - this change will break the acceptance tests until the stub data has been updated as part of BTAT-6214

BTAT-6217 Updated payments sub item parser to read 'paymentAmount'

---

app/views/templates/payments/PaymentMessageHelper.scala
test/views/templates/payments/PaymentsHistoryChargeTemplateSpec.scala

As part of this fix I've also added tests for the POA and AA charges in the `PaymentsHistoryChargeTemplateSpec` as these were missed.

Added repayment CSS tag to charges that were missing it

---

app/controllers/AuthorisedController.scala
it/pages/VatDetailsPageSpec.scala
test/controllers/DirectDebitControllerSpec.scala
test/controllers/MakePaymentControllerSpec.scala
test/controllers/OpenPaymentsControllerSpec.scala
test/controllers/PaymentHistoryControllerSpec.scala
test/controllers/VatCertificateControllerSpec.scala
test/controllers/VatDetailsControllerSpec.scala

Also, when user is an agent but access is not allowed on the page, they are redirected to VACLUF agent action page

No active session auto redirects to sign in

---

app/controllers/PaymentHistoryController.scala
app/views/payments/paymentHistory.scala.html
test/controllers/PaymentHistoryControllerSpec.scala

When the previous payments tab was clicked, because it does not call the financial data API, it has no scope of whether there are empty payments in a certain year. It only knows about the ETMP migration date. Therefore it needs to show the relevant year tabs (in all circumstances, i.e. when they click one of the years), even if they are empty.

BTAT-6857 Corrected bug with hidden tab alongside previous payments

---

app/controllers/OpenPaymentsController.scala
app/controllers/VatDetailsController.scala
app/models/payments/OpenPaymentsModel.scala
app/models/payments/Payment.scala
app/views/templates/nextPaymentSection.scala.html
app/views/templates/payments/whatYouOweChargeRow.scala.html
app/views/vatDetails/details.scala.html
it/connectors/FinancialDataConnectorISpec.scala
test/audit/ViewNextOutstandingVatPaymentAuditModelSpec.scala
test/common/TestModels.scala
test/connectors/httpParsers/PaymentsHttpParserSpec.scala
test/controllers/ControllerBaseSpec.scala
test/controllers/OpenPaymentsControllerSpec.scala
test/controllers/VatDetailsControllerSpec.scala
test/models/payments/OpenPaymentsModelSpec.scala
test/models/payments/PaymentSpec.scala
test/models/payments/PaymentsSpec.scala
test/services/PaymentsServiceSpec.scala
test/services/VatDetailsServiceSpec.scala
test/views/payments/OpenPaymentsViewSpec.scala
test/views/templates/NextPaymentSectionTemplateSpec.scala
test/views/templates/payments/WhatYouOweChargeHelperSpec.scala
test/views/templates/payments/WhatYouOweChargeRowTemplateSpec.scala

Test VRNs:
- Overdue payment (no DD flag set): 444444444
- Overdue payments but DD flag is set for one payment due 7 Sep 2017: 555555555

Reintroduced 'overdue' flag to VAT summary and open payments page

---

public/stylesheets/vat-v1.8.css

To see the change, you might have to close the tab and log in again after switching to/merging the branch (I did anyway, which is why the fix seemed inconsistent).
The change is only for small screens so you need to emulate a smartphone screen in the browser

[BTAT-8241] Added CSS to hide menu toggle properly on small screens

---

app/controllers/PaymentHistoryController.scala
app/models/CustomerDetails.scala
app/models/viewModels/PaymentsHistoryViewModel.scala
app/views/payments/PaymentHistory.scala.html
build.sbt
conf/messages
conf/messages.cy
project/plugins.sbt
test/common/TestModels.scala
test/controllers/ControllerBaseSpec.scala
test/controllers/PaymentHistoryControllerSpec.scala
test/views/payments/PaymentHistoryViewSpec.scala

I removed the session logic around retrieving the migrationToETMPDate because the customer info API call is needed for this additional work anyway.

BTAT-8877 Added insolvency content to the Payment History page

---

app/config/filters/ServiceFilters.scala
app/controllers/SignOutController.scala
app/models/payments/ChargeType.scala
app/testOnly/connectors/BtaStubConnector.scala
app/views/templates/payments/PaymentMessageHelper.scala
build.sbt
project/plugins.sbt
test/common/MessageLookup.scala
test/connectors/ServiceInfoPartialConnectorSpec.scala
test/connectors/httpParsers/PaymentsHistoryHttpParserSpec.scala
test/connectors/httpParsers/PaymentsHttpParserSpec.scala
test/models/PaymentsHistoryModelSpec.scala
test/testOnly/connectors/BtaStubConnectorSpec.scala
test/views/templates/payments/PaymentsHistoryChargeTemplateSpec.scala

After discussion with Jack, Hana and Martin there is no need for new content and we can simply display the existing content but with the appropriate debit or credit styling for the payment history page.

BTAT-9137 Added support for Debit & Credit VAT Default Surcharges

---

app/views/templates/payments/PaymentsHistoryTabsContent.scala.html
test/views/templates/payments/PaymentHistoryTabsContentTemplateSpec.scala

This is in line with the guidance here: https://design-system.service.gov.uk/components/table/#numbers-in-a-table

BTAT-9193 Tweak to accounting view to align numeric columns to the right

---

app/common/SessionKeys.scala
app/connectors/FinancialDataConnector.scala
app/connectors/httpParsers/DirectDebitStatusHttpParser.scala
app/controllers/VatDetailsController.scala
app/models/DDInterruptResult.scala
app/models/DirectDebitStatus.scala
app/services/PaymentsService.scala
it/connectors/FinancialDataConnectorISpec.scala
it/stubs/FinancialDataStub.scala
test/connectors/httpParsers/DirectDebitStatusHttpParserSpec.scala
test/controllers/ControllerBaseSpec.scala
test/controllers/VatDetailsControllerSpec.scala
test/models/DirectDebitStatusSpec.scala
test/services/PaymentsServiceSpec.scala

As part of these changes I removed a small bit of logic in the VAT details controller regarding _reading_ mandation status and migration date from the session. This was to reduce cyclomatic complexity. It's not clear to me why this logic existed as the customer info call is made every time this page loads anyway, so there's no value in branches of logic attempting to read these values from the session. The _writing_ to the session is unaffected.
I was not able to manually test these changes yet as the backend and stub data PRs are not ready. The unit tests should prove the work but we should hold off on the merge until those tasks are ready.

BTAT-9213 Added DD interrupt logic

---

app/assets/stylesheets/application.scss
app/common/SessionKeys.scala
app/controllers/OpenPaymentsController.scala
app/models/viewModels/OpenPaymentsViewModel.scala
app/views/errors/PaymentsError.scala.html
app/views/partials/covid/CovidMessage.scala.html
app/views/payments/NoPayments.scala.html
app/views/payments/OpenPayments.scala.html
app/views/templates/payments/WhatYouOweChargeRow.scala.html
app/views/vatDetails/Details.scala.html
test/controllers/OpenPaymentsControllerSpec.scala
test/views/payments/NoPaymentsViewSpec.scala
test/views/payments/OpenPaymentsViewSpec.scala
test/views/templates/payments/WhatYouOweChargeRowTemplateSpec.scala

As part of this work I found that there were still "has direct debit" elements in the controller, views and view model. The API call to retrieve this status was removed a while ago and so this checking of DD status was pointless, so I have removed it and the related test cases.
Also removed the custom margin that was applied to XL headings, in favour of margin below the breadcrumbs to match the back link.

BTAT-9591 Added agent variants of What You Owe screens

---

app/controllers/PaymentHistoryController.scala
app/models/viewModels/PaymentsHistoryViewModel.scala
app/views/payments/PaymentHistory.scala.html
build.sbt
test/controllers/PaymentHistoryControllerSpec.scala
test/views/payments/PaymentHistoryViewSpec.scala

The agent-specific elements are:
- Client name caption above h1
- Disabling of 'Previous payments' tab and content
- Back link instead of breadcrumbs

BTAT-9592 Added elements to Payment History screen for agents

---

test/controllers/AuthorisedControllerSpec.scala
test/controllers/ControllerBaseSpec.scala
test/controllers/PaymentHistoryControllerSpec.scala
test/controllers/VatCertificateControllerSpec.scala
test/controllers/predicates/AgentPredicateSpec.scala
test/controllers/predicates/FinancialPredicateSpec.scala

Apologies for touching on a few unrelated files here - I changed the customer info mock to prevent needing to repeat `Future.successful` each time it's used.
I've added helper functions in for:
- service info call
- auth (principal, agent, unauthorised, unauthenticated)

BTAT-9726 Refactor to VatCertificateControllerSpec

---

app/connectors/PenaltiesConnector.scala
app/controllers/VatDetailsController.scala
app/models/errors/httpErrors.scala
app/models/penalties/PenaltiesSummary.scala
app/models/viewModels/VatDetailsViewModel.scala
app/services/PenaltiesService.scala
app/views/templates/penalties/PenaltiesBanner.scala.html
app/views/vatDetails/Details.scala.html
conf/messages
it/connectors/PenaltiesConnectorISpec.scala
test/common/TestModels.scala
test/connectors/PenaltiesConnectorSpec.scala
test/controllers/ControllerBaseSpec.scala
test/controllers/VatDetailsControllerSpec.scala
test/models/penalties/PenaltiesSummarySpec.scala
test/services/PenaltiesServiceSpec.scala
test/views/templates/penalties/PenaltiesBannerSpec.scala
test/views/vatDetails/VatDetailsViewSpec.scala

As part of this I also did a small simplification of the penalties API call to remove the `Option` wrapping as this was an unnecessary layer (it's already wrapped in `Either`).

BTAT-9896 Show penalty notification banner

---

app/assets/stylesheets/application.scss
app/views/payments/WhatYouOwe.scala.html
build.sbt
test/views/payments/WhatYouOweViewSpec.scala

The overdue label was moved inside of the button itself in order to fix the alignment issue. I've also added the `tabindex` attribute to the link text so that you can tab to the items in the table with the same behaviour as other links. Other custom CSS was still needed. Here are the explanations:
**.what-you-owe-link**
Ensures the button background does not extend beyond the text on screen, to avoid loading the next page when clicking the nearby empty space
**.what-you-owe-link > govuk-tag**
Disables mouse events for the overdue label itself, to avoid loading the next page when clicking the label
**.what-you-owe-link > a**
Overrides to make the button text look and behave like GOVUK link text

BTAT-10400 Updated WYO CSS to align overdue label and link text

---

app/assets/stylesheets/application.scss
app/views/certificate/VatCertificate.scala.html
app/views/certificate/helpers/StandardReturnFrequency.scala.html
public/stylesheets/print.css
test/views/certificate/VatCertificateViewSpec.scala

I couldn’t change NonStandardReturnFrequency view because summary list doesn’t support our current layout therefore this helper cannot be changed into a twirl component. Another thing to note is the bottom border of the summary list- in staging we don’t have it due to custom css but I’ve ran it by Robin and he agrees we should put the line back in.
I’ve ran wave, axe, validity and also checked the print preview (safari, chrome, Firefox and edge) and all seems fine, but please do double check 🙂 
Here are few VRNs that would be useful to check the different variations of VAT certificate: 999999999, 931564132, 555555555

BTAT-10401 VAT certificate to use GDS components

---

app/models/viewModels/StandardChargeViewModel.scala
app/testOnly/controllers/WhatYouOweController.scala
app/views/payments/ChargeTypeDetailsView.scala.html
app/views/payments/WhatYouOwe.scala.html
app/views/templates/payments/wyoCharges/StandardCharge.scala.html
conf/messages
conf/messages.cy
test/common/TestModels.scala
test/views/payments/ChargeTypeDetailsViewSpec.scala
test/views/payments/WhatYouOweViewSpec.scala

The logic I added recently had a method call to the view model inside the view, which was causing some tight coupling and making the unit tests quite annoying to change, so I refactored this in both the WhatYouOwe view and the charge detail view so that the logic is in the controller instead, which is the better way to do it in general I think

[BTAT-10468] Add link to view VAT return on breakdown pages

---

app/models/viewModels/CrystallisedInterestViewModel.scala
app/views/payments/CrystallisedInterestView.scala.html
build.sbt
conf/messages
test/models/viewModels/CrystallisedInterestViewModelSpec.scala
test/views/payments/CrystallisedInterestViewSpec.scala

The makePaymentRedirect test in the view model was changed due to inconsistent results when running full tests (`sbt test`) compared with running repeat tests inside the sbt interpreter. For some reason in the interpreter when running more than once it would exclude the prod route `/vat-through-software`.

BTAT-10570 Added penalty logic to crystallised interest view

---

app/models/viewModels/CrystallisedInterestViewModel.scala
app/models/viewModels/CrystallisedLPP1ViewModel.scala
app/models/viewModels/EstimatedInterestViewModel.scala
app/views/payments/CrystallisedLPP1View.scala.html
conf/messages
conf/messages.cy
test/models/viewModels/CrystallisedInterestViewModelSpec.scala
test/models/viewModels/CrystallisedLPP1ViewModelSpec.scala
test/views/payments/CrystallisedLPP1ViewSpec.scala

A few notes:
- I confirmed with Martin that we don’t have the guidance link yet; this is set to a placeholder for now
- I confirmed with Anirban that it’s unrealistic that any of the day values will be “1”, so the relevant text is fine to be statically set to the plural “days” and not cater for "day"
- I fixed a bug in a few existing view models that were using an incorrect field for their outstanding amount

BTAT-10614 Added Crystallised LPP1 view & view model

---

app/views/errors/SessionTimeout.scala.html
app/views/payments/EstimatedInterestView.scala.html
app/views/payments/NoPayments.scala.html
app/views/payments/WhatYouOwe.scala.html
build.sbt
test/views/errors/SessionTimeoutViewSpec.scala
test/views/payments/EstimatedInterestViewSpec.scala
test/views/payments/NoPaymentsViewSpec.scala
test/views/payments/WhatYouOweViewSpec.scala

I've checked all the pages and the layout doesn't seem to have changed as shown in the screenshots. This is possibly because the layout issues were addressed by this story: https://jira.tools.tax.service.gov.uk/browse/BTAT-10391

[BTAT-10604] Upgrade to latest play-frontend-hmrc

---

app/models/payments/ChargeType.scala
app/views/templates/payments/PaymentMessageHelper.scala
conf/messages
conf/messages.cy
test/common/MessageLookup.scala
test/connectors/httpParsers/PaymentsHttpParserSpec.scala
test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
test/views/templates/payments/WhatYouOweChargeHelperSpec.scala

Also removed loads of repetitive code in `PaymentsHistoryChargeDescriptionTemplateSpec`, some repetitive messages ("for", "for period", "for the period") and added a few missing tests for 1st LPP penalty charge.

BTAT-10647 Added 4 new interest charge types

---

app/assets/stylesheets/application.scss
app/views/templates/payments/wyoCharges/CrystallisedCharge.scala.html
app/views/templates/payments/wyoCharges/StandardCharge.scala.html
public/stylesheets/vat-v1.8.css
test/views/templates/payments/wyoCharges/CrystallisedChargeViewSpec.scala
test/views/templates/payments/wyoCharges/StandardChargeViewSpec.scala

The validity issue is gone, and I've ran it against Wave and Axe too and there aren't any concerning issues raised (the same usual ones). 
However, in the screenshot attached you can see there is a bit of line between the charge and overdue label, and if you hover over the overdue label and click it will take you to the charge breakdown page, this wasn't present in the old WYO page but caused by the code change I implemented, but if I separate them the Overdue label and charge will be in separate lines. I've been fiddling around with it to sort it out but I have not found a solution for this.

BTAT-10642 WIP

---

app/controllers/VatDetailsController.scala
app/models/payments/Payment.scala
app/models/viewModels/StandardChargeViewModel.scala
app/testOnly/controllers/WhatYouOweController.scala
app/utils/PathBindables.scala
app/views/payments/ChargeTypeDetailsView.scala.html
app/views/payments/CrystallisedInterestView.scala.html
test/common/TestModels.scala
test/models/viewModels/StandardChargeViewModelSpec.scala
test/testOnly/controllers/WhatYouOweControllerSpec.scala
test/utils/PathBindablesSpec.scala
test/views/payments/ChargeTypeDetailsViewSpec.scala

Please wait til after accessibility audit to merge
I also changed the clearedAmount field in the standard charge view model to be non-optional to be consistent with the crystallised interest view model and I changed the path binder unit tests because they were failing with Java 11

[BTAT-10645] Add logic for CrystallisedInterestView

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/repositories/WYOSessionRepository.scala
build.sbt
conf/application.conf
test/mocks/MockAppConfig.scala
test/repositories/WYOSessionRepositorySpec.scala

Attempt number 2 at this PR. The only differences between this PR and #742 are:
- Updated `hmrc-mongo` to 0.67.0
- Changed the TTL index test so that all repository calls are inside of `await` functions and so that `ensureIndexes` is called first
- Set top level vals in the test spec that call the guice app to be lazy

BTAT-10712 Added WYO database and config

---

app/services/WYOSessionService.scala
build.sbt
test/services/WYOSessionServiceSpec.scala

- I have added Mockito dependency as ScalaMock does not play nice with mocking out mongo repositories
- I had to add the reptitive `Json.toJson` line into the write function as there is no JSON writes for the generic type
- I elected to keep the read function simple considering the controller action will need to have a match statement for the view model type again anyway - it seemed pointless to duplicate it
- The tests are quite simple as they are essentially just returning what the database does (extra scenarios would simply be - when I mock a `false`, return `false` - when I mock a `None`, return `None` - etc)

BTAT-10713 Added WYO session service to speak to repository layer

---

app/models/payments/ChargeType.scala
test/models/payments/ChargeTypeSpec.scala

I have added TODO statements for the LPI charges that we currently don't define a parent charge for, to make it clear where the gaps are. The collection I've added will need to be updated when we do the upcoming work for the parent charges.

BTAT-10797 Added charge type -> LPI charge type map

---

app/models/payments/Payment.scala
app/testOnly/controllers/WhatYouOweController.scala
it/connectors/FinancialDataConnectorISpec.scala
test/audit/ViewNextOutstandingVatPaymentAuditModelSpec.scala
test/common/TestModels.scala
test/connectors/httpParsers/PaymentsHttpParserSpec.scala
test/controllers/OpenPaymentsControllerSpec.scala
test/controllers/VatDetailsControllerSpec.scala
test/models/payments/OpenPaymentsModelSpec.scala
test/models/payments/PaymentSpec.scala
test/models/payments/PaymentsSpec.scala
test/services/PaymentsServiceSpec.scala
test/services/VatDetailsServiceSpec.scala
test/testOnly/controllers/WhatYouOweControllerSpec.scala

AT will fail without this stub data change, as originalAmount is now mandatory and the field was missing it caused the page to not load: https://github.com/hmrc/vat-view-change-stub-data/pull/164

BTAT-10901 originalAmount to be mandatory

---

app/controllers/WhatYouOweController.scala
app/models/payments/ChargeType.scala
app/models/payments/Payment.scala
it/connectors/FinancialDataConnectorISpec.scala
it/stubs/FinancialDataStub.scala
test/audit/ViewNextOutstandingVatPaymentAuditModelSpec.scala
test/common/TestModels.scala
test/connectors/httpParsers/PaymentsHttpParserSpec.scala
test/controllers/OpenPaymentsControllerSpec.scala
test/controllers/VatDetailsControllerSpec.scala
test/controllers/WhatYouOweControllerSpec.scala
test/models/payments/OpenPaymentsModelSpec.scala
test/models/payments/PaymentSpec.scala
test/models/payments/PaymentsSpec.scala
test/services/PaymentsServiceSpec.scala
test/services/VatDetailsServiceSpec.scala

Also removed lots of bloat from `Payment` model, and refactored the tests for that model. The many `apply` functions were only being used across various test specs and this was unnecessary. This unfortunately meant making the same change to many test models which clogs up the PR a bit.
Have not been able to manually or acceptance test this yet without stub data

BTAT-11020 Payment reads for interest rate

---

app/config/frontendAppConfig.scala
app/connectors/TimeToPayConnector.scala
app/controllers/TimeToPayController.scala
app/models/TTPRequestModel.scala
app/services/TimeToPayService.scala
conf/app.routes
test/controllers/TimeToPayControllerSpec.scala
test/mocks/MockAppConfig.scala
test/models/TTPRequestModelSpec.scala
test/services/TimeToPayServiceSpec.scala
test/views/payments/WhatYouOweViewSpec.scala

The connector was added so I could fully unit test the service. The function is unimplemented for now but the code is protected by the feature switch.

BTAT-11281 Added route/controller/service layer for TTP API call

---

app/connectors/httpParsers/PenaltyDetailsHttpParser.scala
app/models/penalties/PenaltyDetails.scala
app/services/PenaltyDetailsService.scala
build.sbt
it/connectors/PenaltyDetailsISpec.scala
it/pages/WhatYouOwePageSpec.scala
it/stubs/FinancialDataStub.scala
it/stubs/PenaltyDetailsStub.scala
test/common/TestModels.scala
test/connectors/httpParsers/PenaltyDetailsHttpParserSpec.scala
test/models/penalties/LPPDetailsSpec.scala
test/models/penalties/PenaltyDetailsSpec.scala
test/services/PenaltyDetailsServiceSpec.scala

I added in multiple tests to make sure an empty penalties array with breathing space boolean is supported, as we no longer want to treat no penalty details as 404. A change will be made in the backend to accomodate for this. Please don't merge until the backend work is ready.

BTAT-11290 Added support for breathingSpace boolean

---

app/controllers/WhatYouOweController.scala
test/controllers/WhatYouOweControllerSpec.scala

The build estimates function has been simplified so that it only attempts to find a matching penalty when it needs to, and the estimated LPP function now accepts an optional penalty so it can log a specific message when no match is found.

Updated WYO logging for estimated penalties

---

app/connectors/FinancialDataConnector.scala
app/controllers/PaymentHistoryController.scala
app/services/PaymentsService.scala
it/connectors/FinancialDataConnectorISpec.scala
it/pages/PaymentHistoryPageSpec.scala
it/stubs/FinancialDataStub.scala
test/controllers/PaymentHistoryControllerSpec.scala
test/services/PaymentsServiceSpec.scala

Description of the logic:
If the user has a migration date (meaning either the date they signed up or were migrated to ETMP) within the last 2 years, we use the migration date as the "from" and today's date as the "to".
If the migration date is older than 2 years, or there is no migration date, we use the date 2 years ago as the "from" and today's date as the "to".
We briefly discussed removing the `isLast24Months` function, which was originally written to filter out the oldest payments that could fall in the third calendar year but were outside the 2 year requirement, but I have decided to keep it as a safeguard in case ETMP send us some unexpected older data in our call.

BTAT-11460 Refactor to payment history API call

---

app/audit/models/ViewNextOpenVatObligationAuditModel.scala
app/audit/models/ViewNextOutstandingVatPaymentAuditModel.scala
app/controllers/VatDetailsController.scala
app/services/VatDetailsService.scala
build.sbt
test/audit/ViewNextOpenVatObligationAuditModelSpec.scala
test/audit/ViewNextOutstandingVatPaymentAuditModelSpec.scala
test/controllers/VatDetailsControllerSpec.scala
test/services/VatDetailsServiceSpec.scala

The `date: LocalDate` param in the service function was simply unused so I removed it.
Upgrading hmrc-frontend and bootstrap causes many test failures, so I thought it was not appropriate to tackle those in this task.
Tested manually with Wireshark:

BTAT-11524 Refactor to overview tile auditing to include error scenario

---

app/controllers/WhatYouOweController.scala
test/controllers/ControllerBaseSpec.scala
test/controllers/WhatYouOweControllerSpec.scala

We were incorrectly showing the "no payments" screen when the 1811 call was successful but the 1812 call failed

Fixed bug with WYO API error mixing
