hmrc/vat-summary-frontend

- app/config/filters/WhitelistFilter.scala
- app/config/frontendGlobal.scala
- app/config/frontendWiring.scala
- conf/logback.xml
- project/FrontendBuild.scala
- project/MicroService.scala
Also added some additional logging config for netty
> Upgraded dependencies for service

- app/controllers/ErrorsController.scala
- app/controllers/HelloWorldController.scala
- app/controllers/auth/actions/VatUserAction.scala
- app/views/errors/sessionTimeout.scala.html
- app/views/errors/unauthorised.scala.html
- app/views/helloworld/hello_world.scala.html
- test/controllers/ErrorsControllerSpec.scala
- test/controllers/HelloWorldControllerSpec.scala
- test/views/ViewBaseSpec.scala
- test/views/errors/SessionTimeoutViewSpec.scala
- test/views/errors/UnauthorisedViewSpec.scala
This branch fixes some extra inconsistencies in this repo that were not spotted until now. Appconfig was not being used implicitly, and the view tests were testing the page content incorrectly.
> Changed appConfig to implicit. Updated view tests

- it/partials/VatSectionPageSpec.scala
- it/stubs/AuthStub.scala
Contains:
BTAT-1086
BTAT-1087
BTAT-1088
> BTAT-1086 - BTAT-1088: Partial auth it tests

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/views/templates/nextReturnSection.scala.html
- conf/application.conf
This also needs a change in app-config-base, don't merge this until that is done
> Updated the view returns link on the details page

- app/config/frontendAppConfig.scala
- app/views/vatDetails/details.scala.html
- conf/application.conf
- test/views/vatDetails/VatDetailsViewSpec.scala
Merge with PR of same branch on view-vat-returns-frontend
> Added year path to returns link

- app/connectors/FinancialDataConnector.scala
- app/models/CustomerInformation.scala
- it/stubs/CustomerInfoStub.scala
- it/stubs/FinancialDataStub.scala
- test/connectors/httpParsers/CustomerInfoHttpParserSpec.scala
- test/models/CustomerInformationSpec.scala
Also updated connector to use correct query string parameter.
> BTAT-1734 Refactored CustomerInformation construction

- app/config/ConfigKeys.scala
- app/config/features/Features.scala
- app/controllers/FeatureSwitchController.scala
- app/forms/FeatureSwitchForm.scala
- app/models/FeatureSwitchModel.scala
- app/views/featureSwitch.scala.html
- app/views/templates/accountDetailsSection.scala.html
- app/views/vatDetails/details.scala.html
- conf/application.conf
- conf/messages
- test/views/templates/AccountDetailsSectionTemplateSpec.scala
- test/views/vatDetails/VatDetailsViewSpec.scala
Please do not merge this just yet as it will fail the acceptance tests.
> BTAT-1982 Feature switched account details section

- app/views/govuk_wrapper.scala.html
- app/views/main_template.scala.html
- app/views/payments/openPayments.scala.html
- app/views/templates/expandingHelpSection.scala.html
- public/javascript/vat-v1.js
- test/views/templates/ExpandingHelpSectionTemplateSpec.scala
Also few minor tweaks:
- updated two GA tags to keep consistent format (will update confluence page)
- added missing help section template spec
- removed random 'allowableLosses' id from CGT days
> Fixed progressive disclosure a11y issue

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/controllers/SignOutController.scala
- app/views/errors/sessionTimeout.scala.html
- app/views/errors/unauthorised.scala.html
- app/views/govuk_wrapper.scala.html
- app/views/main_template.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/controllers/SignOutControllerSpec.scala
- test/mocks/MockAppConfig.scala
- test/views/errors/UnauthorisedViewSpec.scala
Also removed sign-out button on session-timeout page
Note: requires an app-config-base PR merged too
> Updated content for unauthorised page

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/controllers/SignOutController.scala
- app/views/govuk_wrapper.scala.html
- conf/app.routes
- conf/application.conf
- test/controllers/SignOutControllerSpec.scala
- test/mocks/MockAppConfig.scala
Can test locally by changing timeout settings in application.conf to short values e.g. period 20 and countdown 10
> BTAT-2474 add timeout warning mechansim

- app/common/FinancialTransactionsConstants.scala
- app/connectors/httpParsers/PaymentsHttpParser.scala
- app/views/templates/payments/WhatYouOweChargeHelper.scala
- conf/messages
- test/connectors/httpParsers/PaymentsHttpParserSpec.scala
Acceptance tests -> https://github.com/hmrc/view-vat-acceptance-tests/pull/134
> [BTAT-4531] added 'VAT Additional Assessment' to 'What you owe' page

- app/models/payments/ChargeType.scala
- app/views/templates/PaymentsHistoryChargeHelper.scala
- conf/messages
- test/views/payments/PaymentHistoryViewSpec.scala
1. chargeType = "VAT FTN RCSL"
mainType = "VAT FTN RCSL"
Amount = "amount"
Date = "clearingDate"
Charge name for heading = "Failure to notify penalty"
Label text = "because you failed to notify us of the date you made a reverse charge sale or stopped making supplies"
2. chargeType = "VAT Failure to submit RCSL"
mainType = VAT Failure to submit RCSL"
Amount = "amount"
Date = "clearingDate"
Charge name for heading = "Reverse Charge sales list penalty"
Label text = "because you have failed to submit a Reverse Charge sales list"
> Added the below chargeTypes

- app/views/templates/vatCertificateSection.scala.html
- app/views/vatDetails/details.scala.html
- build.sbt
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/views/templates/VatCertificateSectionTemplateSpec.scala
- test/views/vatDetails/VatDetailsViewSpec.scala
Please also merge this app-config PR as part of this review:
https://github.com/hmrc/app-config-base/pull/2182
> BTAT-6014 Reworked vat-certificate feature switch to be unlinked from ChoC

- app/config/ConfigKeys.scala
- app/config/features/Features.scala
- app/forms/FeatureSwitchForm.scala
- app/models/FeatureSwitchModel.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/views/featureSwitch.scala.html
- conf/application.conf
> BTAT-6053 Added feature switch for agent access

- conf/messages.cy
Added Welsh translations for vat-summary-frontend.
Checked the ones already existing against the spreadsheet.
Screenshots captured
> Added Welsh translations for vat-summary-frontend.

- app/config/ConfigKeys.scala
- app/config/features/Features.scala
- app/forms/FeatureSwitchForm.scala
- app/models/FeatureSwitchModel.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/views/featureSwitch.scala.html
- conf/application.conf
Please ensure this PR is merged too: https://github.com/hmrc/app-config-production/pull/4808
> BTAT-7044 Added feature switch for MTD sign up

- app/controllers/VatDetailsController.scala
In addition to correcting the warn logging for party type & entity name, I've chosen to remove the rest of the warn logging here as I felt it was redundant (connectors already log API failures). Let me know if you disagree with these decisions.
> BTAT-7844 Cleaned up warn logging in VatDetailsController

- app/config/ConfigKeys.scala
- app/config/features/Features.scala
- app/forms/FeatureSwitchForm.scala
- app/models/FeatureSwitchModel.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/views/FeatureSwitch.scala.html
- conf/application.conf
> [DM] [BTAT-7884] Added new feature switch

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/controllers/VatDetailsController.scala
- app/models/CustomerInformation.scala
- app/testOnly/views/FeatureSwitch.scala.html
- app/views/vatDetails/Details.scala.html
- conf/application.conf
- test/common/TestModels.scala
- test/controllers/VatDetailsControllerSpec.scala
Please ensure the following are merged:
- https://github.com/hmrc/app-config-base/pull/3806
- https://github.com/hmrc/app-config-production/pull/7573
> BTAT-7966-1 Made corrections to email unverified nudge work

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/views/GovUkWrapper.scala.html
- build.sbt
- conf/application.conf
- project/plugins.sbt
- test/mocks/MockAppConfig.scala
Due to the play-ui update, the a11y statement link text is slightly different. Please merge the acceptance test change alongside this to support this change: https://github.com/hmrc/view-vat-acceptance-tests/pull/253
> BTAT-8589 Update GTM script attributes

- README.md
- build.sbt
- project/plugins.sbt
- test/connectors/httpParsers/PaymentsHttpParserSpec.scala
I removed the download line in the readme because it linked to bintray and didn't work anymore
> [BTAT-9354] Update bootstrap and other dependencies

- app/controllers/DDInterruptController.scala
- test/controllers/DDInterruptControllerSpec.scala
While in the `DDInterruptControllerSpec` I refactored the helper function tests to move them away from using the convoluted test Trait with all the service mocks, and added a few more scenarios to the "4 months" function tests that were missing.
> BTAT-9497 Update to DD interrupt logic for validate details scenario

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/connectors/httpParsers/PenaltiesHttpParser.scala
- app/controllers/VatDetailsController.scala
- app/models/viewModels/VatDetailsViewModel.scala
- app/testOnly/controllers/PenaltiesController.scala
- app/testOnly/views/PenaltiesHomeView.scala.html
- app/views/templates/penalties/PenaltiesTileSection.scala.html
- app/views/vatDetails/Details.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- conf/testOnly.routes
- it/connectors/PenaltiesConnectorISpec.scala
- it/stubs/PenaltiesStub.scala
- test/common/TestModels.scala
- test/connectors/httpParsers/PenaltiesHttpParserSpec.scala
- test/controllers/ControllerBaseSpec.scala
- test/controllers/VatDetailsControllerSpec.scala
- test/mocks/MockAppConfig.scala
- test/views/ViewBaseSpec.scala
- test/views/templates/penalties/PenaltiesTileSectionSpec.scala
- test/views/vatDetails/VatDetailsViewSpec.scala
app-config-base PR:  https://github.com/hmrc/app-config-base/pull/6388
> [BTAT-9826] - Added penalties tile and controller logic

- app/models/CustomerInformation.scala
- test/common/TestJson.scala
For a visual demonstration of the issue, use VRN 127142789 and go to the VAT certificate. In Staging currently the stagger is not played back correctly.
> BTAT-10318 Corrected JSON reads for stdReturnPeriod

- app/assets/stylesheets/application.scss
- app/testOnly/controllers/ChargeBreakdownController.scala
- app/views/certificate/VatCertificate.scala.html
- app/views/certificate/helpers/StandardReturnFrequency.scala.html
- app/views/payments/ChargeTypeDetailsView.scala.html
- app/views/templates/payments/WhatYouOweChargeRow.scala.html
- conf/testOnly.routes
- test/testOnly/controllers/ChargeBreakdownControllerSpec.scala
> BTAT-10326 Added route, wire up controller & view for charge breakdown

- app/testOnly/controllers/WhatYouOweController.scala
- it/helpers/IntegrationBaseSpec.scala
- it/pages/WhatYouOwePageSpec.scala
I opted for adding 2 scenarios to check the differences in successful responses (some charges, no charges)
> BTAT-10332 Added IT test for new WYO page

- app/views/templates/NextPaymentSection.scala.html
- app/views/templates/NextReturnSection.scala.html
- app/views/templates/payments/WhatYouOweChargeRow.scala.html
- public/stylesheets/vat-v1.8.css
- test/views/templates/NextPaymentSectionTemplateSpec.scala
- test/views/templates/payments/WhatYouOweChargeRowTemplateSpec.scala
This requires the following AT change:
https://github.com/hmrc/view-vat-acceptance-tests/pull/307
> BTAT-10362 Removed custom overdue CSS, replaced with GOVUK component

- app/config/ConfigKeys.scala
- app/config/features/Features.scala
- app/forms/FeatureSwitchForm.scala
- app/models/FeatureSwitchModel.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/views/featureSwitch/FeatureSwitchItems.scala
- conf/application.conf
- project/plugins.sbt
Please ensure this PR is merged too:
https://github.com/hmrc/app-config-production/pull/14395
> BTAT-10399 Created feature switch for interest breakdown

- app/models/viewModels/InterestChargeViewModel.scala
- app/testOnly/controllers/ChargeBreakdownController.scala
- app/views/payments/WhatYouOwe.scala.html
- conf/testOnly.routes
- test/models/viewModels/InterestChargeViewModelSpec.scala
- test/models/viewModels/VatCertificateViewModelSpec.scala
- test/models/viewModels/WhatYouOweChargeModelSpec.scala
- test/testOnly/controllers/ChargeBreakdownControllerSpec.scala
- test/views/payments/WhatYouOweViewSpec.scala
The route naming is a placeholder until a future story
> BTAT-10397 Created interest charge controller; wiring up with FS & view

- app/models/viewModels/WhatYouOweChargeModel.scala
- app/testOnly/controllers/WhatYouOweController.scala
- app/views/payments/WhatYouOwe.scala.html
- conf/messages
- conf/messages.cy
- test/common/TestModels.scala
- test/controllers/OpenPaymentsControllerSpec.scala
- test/models/viewModels/WhatYouOweChargeModelSpec.scala
- test/testOnly/controllers/ChargeBreakdownControllerSpec.scala
- test/testOnly/controllers/WhatYouOweControllerSpec.scala
- test/views/payments/ChargeTypeDetailsViewSpec.scala
- test/views/payments/WhatYouOweViewSpec.scala
I also added a small unit test for something else to improve coverage
> [BTAT-10451] Add 'view return' link to WhatYouOwe

- app/views/errors/SessionTimeout.scala.html
- app/views/payments/EstimatedInterestView.scala.html
- app/views/payments/NoPayments.scala.html
- app/views/payments/WhatYouOwe.scala.html
- build.sbt
- test/views/errors/SessionTimeoutViewSpec.scala
- test/views/payments/EstimatedInterestViewSpec.scala
- test/views/payments/NoPaymentsViewSpec.scala
- test/views/payments/WhatYouOweViewSpec.scala
Reverts hmrc/vat-summary-frontend#718
> Revert "[BTAT-10604] Upgrade to latest play-frontend-hmrc"

- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
We're obviously missing many Welsh translations from this service currently, so I've added the keys to the Welsh file without the messages
> [BTAT-10613] Audit messages files

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/repositories/WYOSessionRepository.scala
- conf/application.conf
- test/mocks/MockAppConfig.scala
- test/repositories/WYOSessionRepositorySpec.scala
Please also merge the following config PRs:
- https://github.com/hmrc/app-config-qa/pull/15687
- https://github.com/hmrc/app-config-staging/pull/10878
- https://github.com/hmrc/app-config-production/pull/15330
> BTAT-10712 Added WYO database and config

- test/repositories/WYOSessionRepositorySpec.scala
The imported default was 20 seconds, I've doubled it to 40
> BTAT-10712 Increased await timeout for repository spec

- app/config/ConfigKeys.scala
- app/config/features/Features.scala
- app/forms/FeatureSwitchForm.scala
- app/models/FeatureSwitchModel.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/views/featureSwitch/FeatureSwitchItems.scala
- conf/application.conf
- test/config/features/FeatureSpec.scala
App-config-prod PR: https://github.com/hmrc/app-config-production/pull/15464
> BTAT-10739 add overdueTimeToPayDescription FS

- app/models/payments/ChargeType.scala
- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
- test/common/MessageLookup.scala
- test/connectors/httpParsers/PaymentsHttpParserSpec.scala
- test/views/templates/payments/WhatYouOweChargeHelperSpec.scala
Please also merge: https://github.com/hmrc/financial-transactions/pull/80
> BTAT-10758 Adding VAT PA 1st and 2nd LPP LPI Charges

- app/models/payments/ChargeType.scala
- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
- test/common/MessageLookup.scala
- test/connectors/httpParsers/PaymentsHttpParserSpec.scala
- test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
- test/views/templates/payments/WhatYouOweChargeHelperSpec.scala
Accompanying financial-transactions PR: https://github.com/hmrc/financial-transactions/pull/79
> [BTAT-10756] Add VAT PA LPI charge type

- app/models/payments/ChargeType.scala
- app/models/viewModels/EstimatedInterestViewModel.scala
- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
- test/common/MessageLookup.scala
- test/connectors/httpParsers/PaymentsHttpParserSpec.scala
- test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
https://github.com/hmrc/financial-transactions/pull/82
> [BTAT-10656] Add AA LPP LPI charge types

- app/models/viewModels/PaymentsHistoryModel.scala
I haven't added any tests as their already was one when we did this work originally and can confirm that it is still passing
> [BTAT-10818] - Updated logic for allocated to charge logic in Payment History Model

- app/audit/models/ViewVatPaymentHistoryAuditModel.scala
- app/common/FinancialTransactionsConstants.scala
- app/models/payments/TransactionSubItem.scala
- app/models/viewModels/PaymentsHistoryModel.scala
- it/stubs/FinancialDataStub.scala
- test/audit/ViewVatPaymentHistoryAuditModelSpec.scala
- test/connectors/httpParsers/PaymentsHistoryHttpParserSpec.scala
- test/models/PaymentsHistoryModelSpec.scala
Manually tested with a few users from stub data branch BTAT-10817, and the values seem to align with Staging
> BTAT-10820 Modified payment history data field

- app/views/payments/CrystallisedLPP1View.scala.html
- app/views/payments/CrystallisedLPP2View.scala.html
- app/views/payments/EstimatedLPP1View.scala.html
- app/views/payments/EstimatedLPP2View.scala.html
- app/views/payments/LateSubmissionPenaltyView.scala.html
- conf/messages
- conf/messages.cy
- test/views/payments/CrystallisedLPP1ViewSpec.scala
- test/views/payments/CrystallisedLPP2ViewSpec.scala
- test/views/payments/EstimatedLPP1ViewSpec.scala
- test/views/payments/EstimatedLPP2ViewSpec.scala
- test/views/payments/LateSubmissionPenaltyViewSpec.scala
I also noticed that the Late Submission Penalty was opening the the penalties service in a new tab so I have removed this.
> BTAT-11044 Updating LPP links to penalties service

- app/config/ConfigKeys.scala
- app/config/frontendAppConfig.scala
- app/views/templates/penalties/PenaltiesBanner.scala.html
- app/views/vatDetails/Details.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/mocks/MockAppConfig.scala
- test/views/templates/penalties/PenaltiesBannerSpec.scala
- test/views/vatDetails/VatDetailsViewSpec.scala
Still missing welsh, but the rest can be reviewed
> BTAT-11034 new penalties banner

- app/audit/models/HybridPHModel.scala
- app/audit/models/HybridWYOModel.scala
- app/controllers/AuthorisedController.scala
- app/controllers/PaymentHistoryController.scala
- app/controllers/PortalController.scala
- app/controllers/SignOutController.scala
- app/controllers/VatCertificateController.scala
- app/controllers/VatDetailsController.scala
- app/testOnly/controllers/PaymentsStubController.scala
- build.sbt
- project/plugins.sbt
- test/controllers/ControllerBaseSpec.scala
- test/controllers/PaymentHistoryControllerSpec.scala
- test/views/ViewBaseSpec.scala
- test/views/payments/ChargeTypeDetailsViewSpec.scala
- test/views/templates/payments/WhatYouOweChargeHelperSpec.scala
Please merge with:
**Service-manager-config PR:** https://github.com/hmrc/service-manager-config/pull/4809
**Build-jobs PR:** https://github.com/hmrc/build-jobs/pull/12205
> BTAT-11069 vat-summary-frontend scala upgrade 2.13

- app/assets/stylesheets/application.scss
- app/views/templates/payments/PaymentsHistoryChargeDescription.scala.html
- app/views/templates/payments/wyoCharges/CrystallisedCharge.scala.html
- app/views/templates/payments/wyoCharges/EstimatedCharge.scala.html
- app/views/templates/payments/wyoCharges/StandardCharge.scala.html
- test/views/payments/PaymentHistoryViewSpec.scala
Have checked manually and ran Wave, Validity and Axe.
> BTAT-11259 add custom css to replace govuk-hint

- app/controllers/WhatYouOweController.scala
- app/models/penalties/LPPDetails.scala
- build.sbt
- it/stubs/PenaltyDetailsStub.scala
- test/common/TestModels.scala
> BTAT-11292 add TTP in frontend

- app/models/payments/ChargeType.scala
- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
- test/common/MessageLookup.scala
- test/views/payments/PaymentHistoryViewSpec.scala
- test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
Also got rid of a massive charge type matching function that was unused in a test file. Let me know if you know why this existed or if there's an issue with removing it.
> BTAT-11597 Added support for VAT deferral charge type

- app/models/payments/ChargeType.scala
- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
- test/models/payments/ChargeTypeSpec.scala
- test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
Reverts hmrc/vat-summary-frontend#928
> Revert "[DL-12363] [DL-12375] - added VAT Inaccur in EC Sales LPI and VAT FTN RCSL LPI"

- app/models/payments/ChargeType.scala
- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
- test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
DL-12392 DL-12394 DL-12387 Adding 3 new charge types
Other PRs
https://github.com/hmrc/financial-transactions/pull/169
https://github.com/hmrc/vat-view-change-stub-data/pull/269
> DL-12392 DL-12394 DL-12387 Adding 3 new charge types

- app/models/payments/ChargeType.scala
- app/views/templates/payments/PaymentMessageHelper.scala
- conf/messages
- conf/messages.cy
- test/models/payments/ChargeTypeSpec.scala
- test/views/templates/payments/PaymentsHistoryChargeDescriptionTemplateSpec.scala
> [DL-12363] [DL-12375] - added VAT Inaccur in EC Sales LPI and VAT FTN RCSL LPI

- app/controllers/TimeToPayController.scala
- app/forms/FeatureSwitchForm.scala
- app/models/FeatureSwitchModel.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/views/featureSwitch/FeatureSwitchItems.scala
- test/config/features/FeatureSpec.scala
- test/controllers/TimeToPayControllerSpec.scala
- test/views/payments/WhatYouOweViewSpec.scala
> DL-14297 remove overdueTimeToPayDescription.enabled switch

- app/config/ConfigKeys.scala
- app/config/features/Features.scala
- app/config/frontendAppConfig.scala
- app/controllers/VatDetailsController.scala
- app/forms/FeatureSwitchForm.scala
- app/models/CustomerInformation.scala
- app/models/FeatureSwitchModel.scala
- app/models/viewModels/VatDetailsViewModel.scala
- app/services/DateService.scala
- app/testOnly/controllers/FeatureSwitchController.scala
- app/testOnly/views/featureSwitch/FeatureSwitchItems.scala
- app/views/templates/NextPaymentSection.scala.html
- app/views/templates/VatPaymentOnAccountSchedule.scala.html
- app/views/vatDetails/Details.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/common/TestModels.scala
- test/config/features/FeatureSpec.scala
- test/controllers/VatDetailsControllerSpec.scala
- test/mocks/MockAppConfig.scala
- test/views/templates/NextPaymentSectionTemplateSpec.scala
- test/views/vatDetails/VatDetailsViewSpec.scala
> Dl 15508: Added Link to POA Schedule on Manage your VAT Account

- app/views/payments/ExistingDirectDebit.scala.html
- conf/messages
- test/utils/MessagesSpec.scala
> fix apostrophes and add unit test for it

- run.sh
Reverts hmrc/vat-summary-frontend#982
> Revert "possible fix to start VAT_SUMMARY_FRONTEND"
